apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: searxng
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: searxng
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: searxng
    spec:
      containers:
        - env:
            - name: SEARXNG_BASE_URL
              value: https://localhost/
          image: docker.io/searxng/searxng:latest
          name: searxng
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-cm0
            - mountPath: /var/cache/searxng
              name: searxng-data
      restartPolicy: Always
      volumes:
        - configMap:
            name: searxng-cm0
          name: searxng-cm0
        - name: searxng-data
          persistentVolumeClaim:
            claimName: searxng-data
